[package]
name = "borrow_mutex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "^0.3"
thiserror = "^1.0"

[dev-dependencies]
smol = "1.3"
